name: compile
on: [push]

jobs:

  gcc:
    runs-on: gcc:latest
    steps:
      - name: CMake and run test
        run: |
          apt-get update
          apt-get install -y cmake
          cmake -B build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          cmake --build build
          make test -C build

  clang:
    runs-on: silkeh/clang:latest
    steps:
      - name: CMake and run test
        run: |
          cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build
          make test -C build

  icx:
    # using Release build type results in failing tests (21.6.2024)
    runs-on: intel/oneapi-hpckit:latest
    steps:
      - name: CMake and run test
        run: |
          apt-get update --allow-insecure-repositories
          apt-get install --allow-unauthenticated -y cmake
          cmake -B build -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
          make test -C build
